version: '3.8'
name: baemin-elasticsearch-node-adv-khucthienphuc
services:
  baemin-backend-redis:
    container_name: baemin-backend-redis
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - node_network

  baemin-backend-gateway-container:
    container_name: baemin-backend-gateway-container
    build:
      context: .
      dockerfile: ./apps/gateway-api-8080/Dockerfile
    image: baemin-backend-gateway-img
    ports:
      - 8080:8080
    env_file:
      - .env.example
    depends_on:
      - baemin-backend-auth-container
      - baemin-backend-user-container
      - baemin-backend-food-container
      - baemin-backend-cart-container
      - baemin-backend-order-container
      - baemin-backend-voucher-container
    networks:
      - node_network

  baemin-backend-auth-container:
    container_name: baemin-backend-auth-container
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    image: baemin-backend-auth-img
    env_file:
      - .env.example
    networks:
      - node_network

  baemin-backend-user-container:
    container_name: baemin-backend-user-container
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    image: baemin-backend-user-img
    env_file:
      - .env.example
    networks:
      - node_network

  baemin-backend-food-container:
    container_name: baemin-backend-food-container
    build:
      context: .
      dockerfile: ./apps/food/Dockerfile
    image: baemin-backend-food-img
    env_file:
      - .env.example
    depends_on:
      - baemin-backend-redis
    networks:
      - node_network

  baemin-backend-cart-container:
    container_name: baemin-backend-cart-container
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
    image: baemin-backend-cart-img
    env_file:
      - .env.example
    networks:
      - node_network

  baemin-backend-order-container:
    container_name: baemin-backend-order-container
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
    image: baemin-backend-order-img
    env_file:
      - .env.example
    networks:
      - node_network

  baemin-backend-voucher-container:
    container_name: baemin-backend-voucher-container
    build:
      context: .
      dockerfile: ./apps/voucher/Dockerfile
    image: baemin-backend-voucher-img
    env_file:
      - .env.example
    networks:
      - node_network

networks:
  node_network:
    external: true
