const MICROSERVICE_URL = 'RABBITMQ_URL';
const AUTH_SERVICE_NAME = 'AUTH_SERVICE_NAME';
const AUTH_QUEUE = 'RABBITMQ_AUTH_QUEUE';
const USER_SERVICE_NAME = 'USER_SERVICE_NAME';
const USER_QUEUE = 'RABBITMQ_USER_QUEUE';
const FOOD_SERVICE_NAME = 'FOOD_SERVICE_NAME';
const FOOD_QUEUE = 'RABBITMQ_FOOD_QUEUE';
const CART_SERVICE_NAME = 'CART_SERVICE_NAME';
const CART_QUEUE = 'RABBITMQ_CART_QUEUE';
const ORDER_SERVICE_NAME = 'ORDER_SERVICE_NAME';
const ORDER_QUEUE = 'RABBITMQ_ORDER_QUEUE';
const VOUCHER_SERVICE_NAME = 'VOUCHER_SERVICE_NAME';
const VOUCHER_QUEUE = 'RABBITMQ_VOUCHER_QUEUE';

export {
  MICROSERVICE_URL,
  AUTH_SERVICE_NAME,
  AUTH_QUEUE,
  USER_SERVICE_NAME,
  USER_QUEUE,
  FOOD_SERVICE_NAME,
  FOOD_QUEUE,
  CART_SERVICE_NAME,
  CART_QUEUE,
  ORDER_SERVICE_NAME,
  ORDER_QUEUE,
  VOUCHER_SERVICE_NAME,
  VOUCHER_QUEUE,
};
