const AUTH_PATTERN = {
  REGISTER: 'BAEMIN_AUTH_REGISTER',
  LOGIN: 'BAEMIN_AUTH_LOGIN',
  AUTHEN: 'BAEMIN_AUTH_AUTHENTICATION',
};

const USER_PATTERN = {
  ADDRESS: 'BAEMIN_USER_ADDRESS',
  PROFILE: 'BAEMIN_USER_PROFILE',
};

const FOOD_PATTERN = {
  LIST: 'BAEMIN_FOOD_LIST',
  TODAY_FOOD: 'BAEMIN_FOOD_TODAY',
  GET_BY_ID: 'BAEMIN_FOOD_GET_BY_ID',
  CHECK_STOCK: 'BAEMIN_FOOD_CHECK_STOCK',
};

const CART_PATTERN = {
  LIST: 'BAEMIN_CART_LIST',
  TOTAL: 'BAEMIN_CART_TOTAL',
  ADD: 'BAEMIN_CART_ADD',
  UPDATE: 'BAEMIN_CART_UPDATE',
  REMOVE: 'BAEMIN_CART_REMOVE',
  VALIDATE: 'BAEMIN_CART_VALIDATE',
};

export { AUTH_PATTERN, USER_PATTERN, FOOD_PATTERN, CART_PATTERN };
