const AUTH_PATTERN = {
  REGISTER: 'BAEMIN_AUTH_REGISTER',
  LOGIN: 'BAEMIN_AUTH_LOGIN',
  AUTHEN: 'BAEMIN_AUTH_AUTHENTICATION',
};

const USER_PATTERN = {
  ADDRESS: 'BAEMIN_USER_ADDRESS',
  PROFILE: 'BAEMIN_USER_PROFILE',
};

export { AUTH_PATTERN, USER_PATTERN };
