const AUTH_PATTERN = {
  REGISTER: 'BAEMIN_AUTH_REGISTER',
  LOGIN: 'BAEMIN_AUTH_LOGIN',
  AUTHEN: 'BAEMIN_AUTH_AUTHENTICATION',
};

const USER_PATTERN = {
  ADDRESS: 'BAEMIN_USER_ADDRESS',
  VALIDATE_ADDRESS: 'BAEMIN_USER_VALIDATE_ADDRESS',
  PROFILE: 'BAEMIN_USER_PROFILE',
};

const FOOD_PATTERN = {
  LIST: 'BAEMIN_FOOD_LIST',
  TODAY_FOOD: 'BAEMIN_FOOD_TODAY',
  GET_BY_ID: 'BAEMIN_FOOD_GET_BY_ID',
  UPDATE: 'BAEMIN_FOOD_UPDATE',
  CHECK_STOCK: 'BAEMIN_FOOD_CHECK_STOCK',
  VALIDATE_FOOD_IN_STORE: 'BAEMIN_FOOD_VALIDATE_FOOD_IN_STORE',
  STORE_DETAIL: 'BAEMIN_STORE_DETAIL',
  STORE_AND_SHIPPING_PARTNER: 'BAEMIN_STORE_AND_SHIPPING_PARTNER',
  STORE_VALIDATE_SHIPPING_METHOD: 'BAEMIN_STORE_VALIDATE_SHIPPING_METHOD',
  MENU_LIST: 'BAEMIN_MENU_LIST',
  BANNER_LIST: 'BAEMIN_BANNER_LIST',
};

const CART_PATTERN = {
  LIST: 'BAEMIN_CART_LIST',
  TOTAL: 'BAEMIN_CART_TOTAL',
  ADD: 'BAEMIN_CART_ADD',
  UPDATE: 'BAEMIN_CART_UPDATE',
  REMOVE: 'BAEMIN_CART_REMOVE',
  REMOVE_MANY: 'BAEMIN_CART_REMOVE_MANY',
  VALIDATE: 'BAEMIN_CART_VALIDATE',
};

const ORDER_PATTERN = {
  VALIDATE_CREATE_BODY: 'BAEMIN_ORDER_VALIDATE_CREATE_BODY',
  PLACE_ORDER: 'BAEMIN_ORDER_PLACE_ORDER',
  DETAIL: 'BAEMIN_ORDER_DETAIL',
};

const VOUCHER_PATTERN = {
  LIST: 'BAEMIN_VOUCHER_LIST',
  DETAIL: 'BAEMIN_VOUCHER_DETAIL',
};

export {
  AUTH_PATTERN,
  USER_PATTERN,
  FOOD_PATTERN,
  CART_PATTERN,
  ORDER_PATTERN,
  VOUCHER_PATTERN,
};
